// Static ETF holdings — top 20 per fund (updated Q1 2025)
// Physical ETFs (GLD, IBIT) have no stock holdings by design

const STATIC = {
  VOO: [
    { sym: "AAPL",  name: "Apple Inc",                  weight: 7.0 },
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 6.5 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 6.0 },
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 3.8 },
    { sym: "META",  name: "Meta Platforms",             weight: 2.8 },
    { sym: "GOOGL", name: "Alphabet Inc Class A",       weight: 2.2 },
    { sym: "GOOG",  name: "Alphabet Inc Class C",       weight: 1.9 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 1.8 },
    { sym: "BRK.B", name: "Berkshire Hathaway B",       weight: 1.7 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 1.6 },
    { sym: "JPM",   name: "JPMorgan Chase",             weight: 1.5 },
    { sym: "LLY",   name: "Eli Lilly & Co",             weight: 1.3 },
    { sym: "V",     name: "Visa Inc",                   weight: 1.2 },
    { sym: "UNH",   name: "UnitedHealth Group",         weight: 1.1 },
    { sym: "XOM",   name: "Exxon Mobil Corp",           weight: 1.1 },
    { sym: "MA",    name: "Mastercard Inc",             weight: 1.0 },
    { sym: "COST",  name: "Costco Wholesale",           weight: 0.9 },
    { sym: "HD",    name: "Home Depot",                 weight: 0.9 },
    { sym: "NFLX",  name: "Netflix Inc",                weight: 0.8 },
    { sym: "JNJ",   name: "Johnson & Johnson",          weight: 0.8 },
  ],
  XLK: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 22.0 },
    { sym: "AAPL",  name: "Apple Inc",                  weight: 19.5 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 16.5 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 5.5 },
    { sym: "ORCL",  name: "Oracle Corp",                weight: 3.5 },
    { sym: "CRM",   name: "Salesforce Inc",             weight: 3.0 },
    { sym: "AMD",   name: "Advanced Micro Devices",     weight: 2.5 },
    { sym: "CSCO",  name: "Cisco Systems",              weight: 2.0 },
    { sym: "ACN",   name: "Accenture plc",              weight: 2.0 },
    { sym: "IBM",   name: "IBM Corp",                   weight: 1.5 },
    { sym: "INTU",  name: "Intuit Inc",                 weight: 1.4 },
    { sym: "NOW",   name: "ServiceNow Inc",             weight: 1.3 },
    { sym: "ADBE",  name: "Adobe Inc",                  weight: 1.3 },
    { sym: "TXN",   name: "Texas Instruments",          weight: 1.2 },
    { sym: "QCOM",  name: "Qualcomm Inc",               weight: 1.1 },
    { sym: "AMAT",  name: "Applied Materials",          weight: 1.0 },
    { sym: "PLTR",  name: "Palantir Technologies",      weight: 1.0 },
    { sym: "MU",    name: "Micron Technology",          weight: 0.9 },
    { sym: "LRCX",  name: "Lam Research Corp",          weight: 0.8 },
    { sym: "PANW",  name: "Palo Alto Networks",         weight: 0.8 },
  ],
  XLY: [
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 24.0 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 14.0 },
    { sym: "HD",    name: "Home Depot",                 weight: 8.5 },
    { sym: "MCD",   name: "McDonald's Corp",            weight: 4.5 },
    { sym: "BKNG",  name: "Booking Holdings",           weight: 4.0 },
    { sym: "NKE",   name: "Nike Inc",                   weight: 3.5 },
    { sym: "LOW",   name: "Lowe's Companies",           weight: 3.5 },
    { sym: "TJX",   name: "TJX Companies",              weight: 3.0 },
    { sym: "SBUX",  name: "Starbucks Corp",             weight: 2.5 },
    { sym: "CMG",   name: "Chipotle Mexican Grill",     weight: 2.0 },
    { sym: "ABNB",  name: "Airbnb Inc",                 weight: 1.8 },
    { sym: "RCL",   name: "Royal Caribbean Cruises",    weight: 1.5 },
    { sym: "GM",    name: "General Motors",             weight: 1.5 },
    { sym: "F",     name: "Ford Motor Company",         weight: 1.4 },
    { sym: "ORLY",  name: "O'Reilly Automotive",        weight: 1.3 },
    { sym: "AZO",   name: "AutoZone Inc",               weight: 1.2 },
    { sym: "HLT",   name: "Hilton Worldwide Holdings",  weight: 1.1 },
    { sym: "YUM",   name: "Yum! Brands",                weight: 1.0 },
    { sym: "MAR",   name: "Marriott International",     weight: 1.0 },
    { sym: "EBAY",  name: "eBay Inc",                   weight: 0.9 },
  ],
  XLF: [
    { sym: "BRK.B", name: "Berkshire Hathaway B",       weight: 13.5 },
    { sym: "JPM",   name: "JPMorgan Chase",             weight: 11.0 },
    { sym: "V",     name: "Visa Inc",                   weight: 7.5 },
    { sym: "MA",    name: "Mastercard Inc",             weight: 6.0 },
    { sym: "BAC",   name: "Bank of America",            weight: 4.5 },
    { sym: "WFC",   name: "Wells Fargo",                weight: 4.0 },
    { sym: "GS",    name: "Goldman Sachs",              weight: 3.5 },
    { sym: "MS",    name: "Morgan Stanley",             weight: 3.0 },
    { sym: "SPGI",  name: "S&P Global Inc",             weight: 2.5 },
    { sym: "AXP",   name: "American Express",           weight: 2.5 },
    { sym: "BLK",   name: "BlackRock Inc",              weight: 2.0 },
    { sym: "SCHW",  name: "Charles Schwab",             weight: 2.0 },
    { sym: "CB",    name: "Chubb Ltd",                  weight: 1.8 },
    { sym: "C",     name: "Citigroup Inc",              weight: 1.8 },
    { sym: "PGR",   name: "Progressive Corp",           weight: 1.5 },
    { sym: "USB",   name: "U.S. Bancorp",               weight: 1.5 },
    { sym: "COF",   name: "Capital One Financial",      weight: 1.4 },
    { sym: "AON",   name: "Aon plc",                    weight: 1.3 },
    { sym: "MMC",   name: "Marsh & McLennan",           weight: 1.2 },
    { sym: "ICE",   name: "Intercontinental Exchange",  weight: 1.2 },
  ],
  XLI: [
    { sym: "GE",    name: "GE Aerospace",               weight: 5.5 },
    { sym: "CAT",   name: "Caterpillar Inc",            weight: 5.0 },
    { sym: "RTX",   name: "RTX Corporation",            weight: 4.5 },
    { sym: "HON",   name: "Honeywell International",    weight: 4.0 },
    { sym: "UNP",   name: "Union Pacific Corp",         weight: 4.0 },
    { sym: "DE",    name: "Deere & Company",            weight: 3.5 },
    { sym: "LMT",   name: "Lockheed Martin",            weight: 3.5 },
    { sym: "BA",    name: "Boeing Company",             weight: 3.0 },
    { sym: "ETN",   name: "Eaton Corp plc",             weight: 2.5 },
    { sym: "EMR",   name: "Emerson Electric",           weight: 2.5 },
    { sym: "WM",    name: "Waste Management",           weight: 2.0 },
    { sym: "NSC",   name: "Norfolk Southern",           weight: 1.8 },
    { sym: "CSX",   name: "CSX Corporation",            weight: 1.7 },
    { sym: "ITW",   name: "Illinois Tool Works",        weight: 1.5 },
    { sym: "CTAS",  name: "Cintas Corp",                weight: 1.4 },
    { sym: "GD",    name: "General Dynamics",           weight: 1.3 },
    { sym: "PCAR",  name: "PACCAR Inc",                 weight: 1.3 },
    { sym: "FDX",   name: "FedEx Corp",                 weight: 1.2 },
    { sym: "MMM",   name: "3M Company",                 weight: 1.2 },
    { sym: "ADP",   name: "Automatic Data Processing",  weight: 1.1 },
  ],
  XLE: [
    { sym: "XOM",   name: "Exxon Mobil Corp",           weight: 22.0 },
    { sym: "CVX",   name: "Chevron Corp",               weight: 15.5 },
    { sym: "COP",   name: "ConocoPhillips",             weight: 7.0 },
    { sym: "EOG",   name: "EOG Resources",              weight: 5.0 },
    { sym: "SLB",   name: "SLB",                        weight: 4.5 },
    { sym: "MPC",   name: "Marathon Petroleum",         weight: 4.0 },
    { sym: "PSX",   name: "Phillips 66",                weight: 4.0 },
    { sym: "OXY",   name: "Occidental Petroleum",       weight: 3.5 },
    { sym: "WMB",   name: "Williams Companies",         weight: 3.0 },
    { sym: "DVN",   name: "Devon Energy",               weight: 2.5 },
    { sym: "HAL",   name: "Halliburton Company",        weight: 2.5 },
    { sym: "FANG",  name: "Diamondback Energy",         weight: 2.0 },
    { sym: "BKR",   name: "Baker Hughes",               weight: 2.0 },
    { sym: "VLO",   name: "Valero Energy",              weight: 2.0 },
    { sym: "KMI",   name: "Kinder Morgan",              weight: 1.8 },
    { sym: "HES",   name: "Hess Corporation",           weight: 1.5 },
    { sym: "TRGP",  name: "Targa Resources",            weight: 1.5 },
    { sym: "EQT",   name: "EQT Corporation",            weight: 1.3 },
    { sym: "MRO",   name: "Marathon Oil",               weight: 1.2 },
    { sym: "APA",   name: "APA Corporation",            weight: 1.0 },
  ],
  XLV: [
    { sym: "LLY",   name: "Eli Lilly & Co",             weight: 12.0 },
    { sym: "UNH",   name: "UnitedHealth Group",         weight: 10.5 },
    { sym: "ABBV",  name: "AbbVie Inc",                 weight: 6.0 },
    { sym: "JNJ",   name: "Johnson & Johnson",          weight: 5.5 },
    { sym: "MRK",   name: "Merck & Co",                 weight: 5.0 },
    { sym: "ABT",   name: "Abbott Laboratories",        weight: 4.5 },
    { sym: "TMO",   name: "Thermo Fisher Scientific",   weight: 4.0 },
    { sym: "ISRG",  name: "Intuitive Surgical",         weight: 3.5 },
    { sym: "DHR",   name: "Danaher Corp",               weight: 3.0 },
    { sym: "BSX",   name: "Boston Scientific",          weight: 2.5 },
    { sym: "AMGN",  name: "Amgen Inc",                  weight: 2.5 },
    { sym: "SYK",   name: "Stryker Corp",               weight: 2.0 },
    { sym: "MDT",   name: "Medtronic plc",              weight: 2.0 },
    { sym: "VRTX",  name: "Vertex Pharmaceuticals",     weight: 1.8 },
    { sym: "BMY",   name: "Bristol-Myers Squibb",       weight: 1.8 },
    { sym: "CVS",   name: "CVS Health",                 weight: 1.5 },
    { sym: "HCA",   name: "HCA Healthcare",             weight: 1.5 },
    { sym: "ELV",   name: "Elevance Health",            weight: 1.3 },
    { sym: "DXCM",  name: "Dexcom Inc",                 weight: 1.0 },
    { sym: "BAX",   name: "Baxter International",       weight: 1.0 },
  ],
  XLP: [
    { sym: "PG",    name: "Procter & Gamble",           weight: 15.0 },
    { sym: "COST",  name: "Costco Wholesale",           weight: 12.5 },
    { sym: "KO",    name: "Coca-Cola Company",          weight: 9.0 },
    { sym: "PEP",   name: "PepsiCo Inc",                weight: 8.5 },
    { sym: "PM",    name: "Philip Morris International",weight: 6.0 },
    { sym: "WMT",   name: "Walmart Inc",                weight: 5.5 },
    { sym: "MDLZ",  name: "Mondelez International",     weight: 4.0 },
    { sym: "MO",    name: "Altria Group",               weight: 3.5 },
    { sym: "CL",    name: "Colgate-Palmolive",          weight: 3.0 },
    { sym: "GIS",   name: "General Mills",              weight: 2.5 },
    { sym: "KMB",   name: "Kimberly-Clark",             weight: 2.0 },
    { sym: "SYY",   name: "Sysco Corporation",          weight: 1.8 },
    { sym: "STZ",   name: "Constellation Brands",       weight: 1.5 },
    { sym: "HSY",   name: "Hershey Company",            weight: 1.5 },
    { sym: "TSN",   name: "Tyson Foods",                weight: 1.3 },
    { sym: "HRL",   name: "Hormel Foods",               weight: 1.2 },
    { sym: "EL",    name: "Estee Lauder",               weight: 1.2 },
    { sym: "K",     name: "Kellanova",                  weight: 1.0 },
    { sym: "CAG",   name: "Conagra Brands",             weight: 1.0 },
    { sym: "CPB",   name: "Campbell Soup",              weight: 0.8 },
  ],
  XLB: [
    { sym: "LIN",   name: "Linde plc",                  weight: 17.0 },
    { sym: "APD",   name: "Air Products & Chemicals",   weight: 6.5 },
    { sym: "SHW",   name: "Sherwin-Williams",           weight: 6.5 },
    { sym: "ECL",   name: "Ecolab Inc",                 weight: 5.5 },
    { sym: "NEM",   name: "Newmont Corp",               weight: 5.0 },
    { sym: "FCX",   name: "Freeport-McMoRan",           weight: 4.5 },
    { sym: "DOW",   name: "Dow Inc",                    weight: 4.0 },
    { sym: "DD",    name: "DuPont de Nemours",          weight: 3.5 },
    { sym: "PPG",   name: "PPG Industries",             weight: 3.5 },
    { sym: "VMC",   name: "Vulcan Materials",           weight: 3.0 },
    { sym: "ALB",   name: "Albemarle Corp",             weight: 2.5 },
    { sym: "EMN",   name: "Eastman Chemical",           weight: 2.0 },
    { sym: "CE",    name: "Celanese Corp",              weight: 2.0 },
    { sym: "IFF",   name: "Intl Flavors & Fragrances",  weight: 1.8 },
    { sym: "CF",    name: "CF Industries",              weight: 1.5 },
    { sym: "MOS",   name: "Mosaic Company",             weight: 1.5 },
    { sym: "RPM",   name: "RPM International",          weight: 1.3 },
    { sym: "FMC",   name: "FMC Corporation",            weight: 1.3 },
    { sym: "BALL",  name: "Ball Corporation",           weight: 1.2 },
    { sym: "AVY",   name: "Avery Dennison",             weight: 1.0 },
  ],
  SMH: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 20.5 },
    { sym: "TSM",   name: "Taiwan Semiconductor Mfg",   weight: 13.0 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 8.5 },
    { sym: "ASML",  name: "ASML Holding NV",            weight: 5.5 },
    { sym: "AMD",   name: "Advanced Micro Devices",     weight: 4.5 },
    { sym: "TXN",   name: "Texas Instruments",          weight: 4.5 },
    { sym: "AMAT",  name: "Applied Materials",          weight: 4.0 },
    { sym: "QCOM",  name: "Qualcomm Inc",               weight: 3.5 },
    { sym: "LRCX",  name: "Lam Research Corp",          weight: 3.0 },
    { sym: "KLAC",  name: "KLA Corporation",            weight: 2.5 },
    { sym: "MU",    name: "Micron Technology",          weight: 2.5 },
    { sym: "INTC",  name: "Intel Corp",                 weight: 2.5 },
    { sym: "MRVL",  name: "Marvell Technology",         weight: 2.0 },
    { sym: "ON",    name: "ON Semiconductor",           weight: 1.8 },
    { sym: "NXPI",  name: "NXP Semiconductors",         weight: 1.5 },
    { sym: "MPWR",  name: "Monolithic Power Systems",   weight: 1.5 },
    { sym: "ADI",   name: "Analog Devices",             weight: 1.4 },
    { sym: "STM",   name: "STMicroelectronics",         weight: 1.3 },
    { sym: "ENTG",  name: "Entegris Inc",               weight: 1.0 },
    { sym: "WOLF",  name: "Wolfspeed Inc",              weight: 1.0 },
  ],
  IGV: [
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 8.5 },
    { sym: "ORCL",  name: "Oracle Corp",                weight: 8.0 },
    { sym: "ADBE",  name: "Adobe Inc",                  weight: 7.5 },
    { sym: "NOW",   name: "ServiceNow Inc",             weight: 7.0 },
    { sym: "INTU",  name: "Intuit Inc",                 weight: 6.5 },
    { sym: "CDNS",  name: "Cadence Design Systems",     weight: 5.0 },
    { sym: "SNPS",  name: "Synopsys Inc",               weight: 4.5 },
    { sym: "SAP",   name: "SAP SE",                     weight: 4.0 },
    { sym: "WDAY",  name: "Workday Inc",                weight: 3.5 },
    { sym: "PANW",  name: "Palo Alto Networks",         weight: 3.0 },
    { sym: "CRWD",  name: "CrowdStrike Holdings",       weight: 2.5 },
    { sym: "TEAM",  name: "Atlassian Corp",             weight: 2.5 },
    { sym: "DDOG",  name: "Datadog Inc",                weight: 2.0 },
    { sym: "ZS",    name: "Zscaler Inc",                weight: 2.0 },
    { sym: "FTNT",  name: "Fortinet Inc",               weight: 1.8 },
    { sym: "HUBS",  name: "HubSpot Inc",                weight: 1.5 },
    { sym: "OKTA",  name: "Okta Inc",                   weight: 1.5 },
    { sym: "DOCU",  name: "DocuSign Inc",               weight: 1.3 },
    { sym: "ZI",    name: "ZoomInfo Technologies",      weight: 1.2 },
    { sym: "SNOW",  name: "Snowflake Inc",              weight: 1.2 },
  ],
  CLOU: [
    { sym: "WDAY",  name: "Workday Inc",                weight: 4.5 },
    { sym: "ZS",    name: "Zscaler Inc",                weight: 4.5 },
    { sym: "DDOG",  name: "Datadog Inc",                weight: 4.5 },
    { sym: "MDB",   name: "MongoDB Inc",                weight: 4.0 },
    { sym: "SNOW",  name: "Snowflake Inc",              weight: 4.0 },
    { sym: "CFLT",  name: "Confluent Inc",              weight: 3.5 },
    { sym: "ESTC",  name: "Elastic NV",                 weight: 3.5 },
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 3.5 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 3.5 },
    { sym: "GOOGL", name: "Alphabet Inc",               weight: 3.5 },
    { sym: "TWLO",  name: "Twilio Inc",                 weight: 3.0 },
    { sym: "OKTA",  name: "Okta Inc",                   weight: 3.0 },
    { sym: "HUBS",  name: "HubSpot Inc",                weight: 2.5 },
    { sym: "DOCU",  name: "DocuSign Inc",               weight: 2.5 },
    { sym: "ZI",    name: "ZoomInfo Technologies",      weight: 2.5 },
    { sym: "PCTY",  name: "Paylocity Holding",          weight: 2.0 },
    { sym: "BILL",  name: "Bill.com Holdings",          weight: 2.0 },
    { sym: "RNG",   name: "RingCentral Inc",            weight: 2.0 },
    { sym: "BOX",   name: "Box Inc",                    weight: 1.8 },
    { sym: "FIVN",  name: "Five9 Inc",                  weight: 1.5 },
  ],
  CIBR: [
    { sym: "PANW",  name: "Palo Alto Networks",         weight: 5.5 },
    { sym: "CRWD",  name: "CrowdStrike Holdings",       weight: 5.5 },
    { sym: "FTNT",  name: "Fortinet Inc",               weight: 5.0 },
    { sym: "CSCO",  name: "Cisco Systems",              weight: 4.5 },
    { sym: "CYBR",  name: "CyberArk Software",          weight: 4.0 },
    { sym: "CHKP",  name: "Check Point Software",       weight: 3.5 },
    { sym: "GEN",   name: "Gen Digital Inc",            weight: 3.5 },
    { sym: "S",     name: "SentinelOne",                weight: 3.5 },
    { sym: "QLYS",  name: "Qualys Inc",                 weight: 3.0 },
    { sym: "VRNS",  name: "Varonis Systems",            weight: 3.0 },
    { sym: "ZS",    name: "Zscaler Inc",                weight: 2.5 },
    { sym: "OKTA",  name: "Okta Inc",                   weight: 2.5 },
    { sym: "TENB",  name: "Tenable Holdings",           weight: 2.0 },
    { sym: "SAIL",  name: "SailPoint Technologies",     weight: 2.0 },
    { sym: "FFIV",  name: "F5 Inc",                     weight: 1.8 },
    { sym: "CACI",  name: "CACI International",         weight: 1.5 },
    { sym: "SAIC",  name: "Science Applications Intl",  weight: 1.5 },
    { sym: "LDOS",  name: "Leidos Holdings",            weight: 1.3 },
    { sym: "BAH",   name: "Booz Allen Hamilton",        weight: 1.3 },
    { sym: "BB",    name: "BlackBerry Ltd",             weight: 1.0 },
  ],
  DTCR: [
    { sym: "EQIX",  name: "Equinix Inc",                weight: 15.5 },
    { sym: "AMT",   name: "American Tower Corp",        weight: 14.5 },
    { sym: "DLR",   name: "Digital Realty Trust",       weight: 9.5 },
    { sym: "CCI",   name: "Crown Castle Inc",           weight: 8.5 },
    { sym: "SBAC",  name: "SBA Communications",         weight: 7.0 },
    { sym: "IRM",   name: "Iron Mountain Inc",          weight: 5.5 },
    { sym: "VRT",   name: "Vertiv Holdings",            weight: 5.0 },
    { sym: "ANET",  name: "Arista Networks",            weight: 4.5 },
    { sym: "NTAP",  name: "NetApp Inc",                 weight: 4.0 },
    { sym: "STX",   name: "Seagate Technology",         weight: 3.5 },
    { sym: "WDC",   name: "Western Digital Corp",       weight: 3.0 },
    { sym: "PSTG",  name: "Pure Storage",               weight: 2.5 },
    { sym: "SMCI",  name: "Super Micro Computer",       weight: 2.5 },
    { sym: "HPE",   name: "Hewlett Packard Enterprise", weight: 2.0 },
    { sym: "DBRG",  name: "DigitalBridge Group",        weight: 1.8 },
    { sym: "CSCO",  name: "Cisco Systems",              weight: 1.5 },
    { sym: "JNPR",  name: "Juniper Networks",           weight: 1.5 },
    { sym: "UNIT",  name: "Uniti Group",                weight: 1.3 },
    { sym: "LUMN",  name: "Lumen Technologies",         weight: 1.0 },
    { sym: "ZAYO",  name: "Zayo Group Holdings",        weight: 1.0 },
  ],
  QTUM: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 5.0 },
    { sym: "IBM",   name: "IBM Corp",                   weight: 4.5 },
    { sym: "GOOG",  name: "Alphabet Inc",               weight: 4.5 },
    { sym: "HON",   name: "Honeywell International",    weight: 4.5 },
    { sym: "IONQ",  name: "IonQ Inc",                   weight: 4.0 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 4.0 },
    { sym: "RGTI",  name: "Rigetti Computing",          weight: 3.5 },
    { sym: "QBTS",  name: "D-Wave Quantum Inc",         weight: 3.5 },
    { sym: "QUBT",  name: "Quantum Computing Inc",      weight: 3.0 },
    { sym: "ARQQ",  name: "Arqit Quantum",              weight: 2.5 },
    { sym: "INTC",  name: "Intel Corp",                 weight: 2.5 },
    { sym: "AMAT",  name: "Applied Materials",          weight: 2.0 },
    { sym: "QCOM",  name: "Qualcomm Inc",               weight: 2.0 },
    { sym: "TXN",   name: "Texas Instruments",          weight: 2.0 },
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 1.8 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 1.5 },
    { sym: "META",  name: "Meta Platforms",             weight: 1.5 },
    { sym: "BIDU",  name: "Baidu Inc",                  weight: 1.3 },
    { sym: "MU",    name: "Micron Technology",          weight: 1.2 },
    { sym: "LRCX",  name: "Lam Research Corp",          weight: 1.0 },
  ],
  BOTZ: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 11.5 },
    { sym: "ABB",   name: "ABB Ltd ADR",                weight: 9.5 },
    { sym: "ISRG",  name: "Intuitive Surgical",         weight: 8.5 },
    { sym: "FANUC", name: "Fanuc Corp ADR",             weight: 7.0 },
    { sym: "SMC",   name: "SMC Corp ADR",               weight: 5.5 },
    { sym: "ROK",   name: "Rockwell Automation",        weight: 4.0 },
    { sym: "OMRON", name: "Omron Corp ADR",             weight: 4.0 },
    { sym: "BRKS",  name: "Brooks Automation",          weight: 3.5 },
    { sym: "AXON",  name: "Axon Enterprise",            weight: 3.0 },
    { sym: "KION",  name: "KION Group ADR",             weight: 3.0 },
    { sym: "KEYENCE",name:"Keyence Corp ADR",           weight: 2.8 },
    { sym: "YASKY", name: "Yaskawa Electric ADR",       weight: 2.5 },
    { sym: "CGNX",  name: "Cognex Corp",                weight: 2.0 },
    { sym: "TRMB",  name: "Trimble Inc",                weight: 1.8 },
    { sym: "TER",   name: "Teradyne Inc",               weight: 1.5 },
    { sym: "NXRT",  name: "NexTracker Inc",             weight: 1.5 },
    { sym: "PATH",  name: "UiPath Inc",                 weight: 1.3 },
    { sym: "AI",    name: "C3.ai Inc",                  weight: 1.3 },
    { sym: "AIOT",  name: "PowerFleet Inc",             weight: 1.0 },
    { sym: "RBOT",  name: "Vicarious Surgical",         weight: 1.0 },
  ],
  ITA: [
    { sym: "RTX",   name: "RTX Corporation",            weight: 19.5 },
    { sym: "LMT",   name: "Lockheed Martin Corp",       weight: 17.5 },
    { sym: "GE",    name: "GE Aerospace",               weight: 12.0 },
    { sym: "NOC",   name: "Northrop Grumman",           weight: 8.5 },
    { sym: "GD",    name: "General Dynamics Corp",      weight: 7.0 },
    { sym: "TDG",   name: "TransDigm Group",            weight: 6.5 },
    { sym: "HII",   name: "Huntington Ingalls",         weight: 4.0 },
    { sym: "LHX",   name: "L3Harris Technologies",      weight: 3.5 },
    { sym: "HWM",   name: "Howmet Aerospace",           weight: 3.0 },
    { sym: "AXON",  name: "Axon Enterprise",            weight: 2.5 },
    { sym: "TDY",   name: "Teledyne Technologies",      weight: 2.0 },
    { sym: "WWD",   name: "Woodward Inc",               weight: 1.8 },
    { sym: "KTOS",  name: "Kratos Defense & Security",  weight: 1.8 },
    { sym: "MOOG",  name: "Moog Inc",                   weight: 1.5 },
    { sym: "DRS",   name: "Leonardo DRS",               weight: 1.5 },
    { sym: "HEI",   name: "HEICO Corp",                 weight: 1.5 },
    { sym: "LDOS",  name: "Leidos Holdings",            weight: 1.3 },
    { sym: "BAH",   name: "Booz Allen Hamilton",        weight: 1.2 },
    { sym: "SPR",   name: "Spirit AeroSystems",         weight: 1.0 },
    { sym: "CW",    name: "Curtiss-Wright Corp",        weight: 1.0 },
  ],
  UFO: [
    { sym: "IRDM",  name: "Iridium Communications",     weight: 7.0 },
    { sym: "BWXT",  name: "BWX Technologies",           weight: 6.5 },
    { sym: "LMT",   name: "Lockheed Martin Corp",       weight: 6.0 },
    { sym: "NOC",   name: "Northrop Grumman",           weight: 5.5 },
    { sym: "KTOS",  name: "Kratos Defense & Security",  weight: 4.5 },
    { sym: "RKLB",  name: "Rocket Lab USA",             weight: 4.5 },
    { sym: "ASTS",  name: "AST SpaceMobile",            weight: 4.0 },
    { sym: "GSAT",  name: "Globalstar Inc",             weight: 3.5 },
    { sym: "VSAT",  name: "ViaSat Inc",                 weight: 3.5 },
    { sym: "PL",    name: "Planet Labs PBC",            weight: 3.0 },
    { sym: "MNTS",  name: "Momentus Inc",               weight: 2.5 },
    { sym: "LLAP",  name: "Terran Orbital",             weight: 2.5 },
    { sym: "BA",    name: "Boeing Company",             weight: 2.5 },
    { sym: "RTX",   name: "RTX Corporation",            weight: 2.0 },
    { sym: "HII",   name: "Huntington Ingalls",         weight: 2.0 },
    { sym: "ASTR",  name: "Astra Space",                weight: 1.8 },
    { sym: "SFET",  name: "Safe-T Group",               weight: 1.5 },
    { sym: "SPCE",  name: "Virgin Galactic Holdings",   weight: 1.5 },
    { sym: "NSAT",  name: "Northern Star Acq Corp",     weight: 1.3 },
    { sym: "GPCR",  name: "Structure Therapeutics",     weight: 1.0 },
  ],
  XBI: [
    { sym: "RXRX",  name: "Recursion Pharmaceuticals",  weight: 2.5 },
    { sym: "ARWR",  name: "Arrowhead Pharmaceuticals",  weight: 2.5 },
    { sym: "PCVX",  name: "Vaxcyte Inc",                weight: 2.5 },
    { sym: "SRPT",  name: "Sarepta Therapeutics",       weight: 2.2 },
    { sym: "GILD",  name: "Gilead Sciences",            weight: 2.0 },
    { sym: "AMGN",  name: "Amgen Inc",                  weight: 2.0 },
    { sym: "VRTX",  name: "Vertex Pharmaceuticals",     weight: 1.8 },
    { sym: "MRNA",  name: "Moderna Inc",                weight: 1.8 },
    { sym: "REGN",  name: "Regeneron Pharmaceuticals",  weight: 1.5 },
    { sym: "BIIB",  name: "Biogen Inc",                 weight: 1.5 },
    { sym: "ALNY",  name: "Alnylam Pharmaceuticals",    weight: 1.5 },
    { sym: "CRSP",  name: "CRISPR Therapeutics",        weight: 1.3 },
    { sym: "NTLA",  name: "Intellia Therapeutics",      weight: 1.3 },
    { sym: "BEAM",  name: "Beam Therapeutics",          weight: 1.2 },
    { sym: "EDIT",  name: "Editas Medicine",            weight: 1.2 },
    { sym: "FATE",  name: "Fate Therapeutics",          weight: 1.2 },
    { sym: "BMRN",  name: "BioMarin Pharmaceutical",    weight: 1.0 },
    { sym: "INCY",  name: "Incyte Corp",                weight: 1.0 },
    { sym: "EXAS",  name: "Exact Sciences",             weight: 1.0 },
    { sym: "BLUE",  name: "bluebird bio",               weight: 0.8 },
  ],
  BKCH: [
    { sym: "COIN",  name: "Coinbase Global",            weight: 18.0 },
    { sym: "MSTR",  name: "MicroStrategy Inc",          weight: 14.0 },
    { sym: "MARA",  name: "Marathon Digital Holdings",  weight: 8.0 },
    { sym: "RIOT",  name: "Riot Platforms Inc",         weight: 7.0 },
    { sym: "CLSK",  name: "CleanSpark Inc",             weight: 5.5 },
    { sym: "HUT",   name: "Hut 8 Corp",                weight: 5.0 },
    { sym: "CIFR",  name: "Cipher Mining Inc",          weight: 4.5 },
    { sym: "WULF",  name: "TeraWulf Inc",               weight: 4.0 },
    { sym: "IREN",  name: "Iris Energy",                weight: 3.5 },
    { sym: "BTBT",  name: "Bit Digital Inc",            weight: 3.0 },
    { sym: "HIVE",  name: "HIVE Digital Technologies",  weight: 2.5 },
    { sym: "BITF",  name: "Bitfarms Ltd",               weight: 2.5 },
    { sym: "SQ",    name: "Block Inc",                  weight: 2.0 },
    { sym: "PYPL",  name: "PayPal Holdings",            weight: 2.0 },
    { sym: "ARBK",  name: "Argo Blockchain",            weight: 1.5 },
    { sym: "GLXY",  name: "Galaxy Digital Holdings",    weight: 1.5 },
    { sym: "DMGI",  name: "DMG Blockchain Solutions",   weight: 1.3 },
    { sym: "CAN",   name: "Canaan Inc",                 weight: 1.3 },
    { sym: "EBON",  name: "Ebang International",        weight: 1.0 },
    { sym: "NKLA",  name: "Nikola Corp",                weight: 0.8 },
  ],
  COPX: [
    { sym: "FCX",   name: "Freeport-McMoRan Inc",       weight: 12.0 },
    { sym: "SCCO",  name: "Southern Copper Corp",       weight: 9.5 },
    { sym: "BHP",   name: "BHP Group Ltd ADR",          weight: 7.5 },
    { sym: "TECK",  name: "Teck Resources Ltd",         weight: 6.5 },
    { sym: "VALE",  name: "Vale SA ADR",                weight: 6.0 },
    { sym: "GLEN",  name: "Glencore plc ADR",           weight: 5.5 },
    { sym: "IVPAF", name: "Ivanhoe Mines Ltd",          weight: 5.0 },
    { sym: "FM",    name: "First Quantum Minerals",     weight: 4.5 },
    { sym: "ERO",   name: "ERO Copper Corp",            weight: 3.5 },
    { sym: "HBM",   name: "HudBay Minerals",            weight: 3.0 },
    { sym: "CPOEF", name: "Capstone Copper Corp",       weight: 2.8 },
    { sym: "RIO",   name: "Rio Tinto plc ADR",          weight: 2.5 },
    { sym: "NGLOY", name: "Anglo American plc ADR",     weight: 2.5 },
    { sym: "CPMC",  name: "Copper Mountain Mining",     weight: 2.0 },
    { sym: "SBSW",  name: "Sibanye Stillwater",         weight: 2.0 },
    { sym: "THLEF", name: "Thalanga Copper Mines",      weight: 1.5 },
    { sym: "TLOFF", name: "Trilogy Metals",             weight: 1.5 },
    { sym: "NGEXF", name: "NGEx Minerals",              weight: 1.3 },
    { sym: "AAUKF", name: "Anglo American plc",         weight: 1.3 },
    { sym: "WDOFF", name: "Western Copper & Gold",      weight: 1.0 },
  ],
  REMX: [
    { sym: "MP",    name: "MP Materials Corp",          weight: 8.0 },
    { sym: "LYNAS", name: "Lynas Rare Earths ADR",      weight: 7.0 },
    { sym: "ILUKA", name: "Iluka Resources ADR",        weight: 5.5 },
    { sym: "AMG",   name: "AMG Advanced Metallurgy",    weight: 5.5 },
    { sym: "UMICORE",name:"Umicore SA ADR",             weight: 5.0 },
    { sym: "NMG",   name: "Nouveau Monde Graphite",     weight: 4.5 },
    { sym: "NB",    name: "NioCorp Developments",       weight: 4.0 },
    { sym: "NOVONIX",name:"Novonix Ltd",                weight: 3.5 },
    { sym: "LAC",   name: "Lithium Americas Corp",      weight: 3.0 },
    { sym: "REE",   name: "REE Automotive",             weight: 2.5 },
    { sym: "SLI",   name: "Standard Lithium",           weight: 2.5 },
    { sym: "LITHY", name: "Lithium Chile Inc",          weight: 2.0 },
    { sym: "SGML",  name: "Sigma Lithium",              weight: 2.0 },
    { sym: "ALTM",  name: "Arcadium Lithium",           weight: 1.8 },
    { sym: "PLTM",  name: "Piedmont Lithium",           weight: 1.8 },
    { sym: "LTHM",  name: "Livent Corp",                weight: 1.5 },
    { sym: "HPMSF", name: "Hyperion Metals Ltd",        weight: 1.5 },
    { sym: "CRML",  name: "Critical Metals Corp",       weight: 1.3 },
    { sym: "REEMF", name: "Ucore Rare Metals",          weight: 1.0 },
    { sym: "REET",  name: "iShares Global REIT ETF",    weight: 0.8 },
  ],
  GRID: [
    { sym: "ITRI",  name: "Itron Inc",                  weight: 6.5 },
    { sym: "PWR",   name: "Quanta Services Inc",        weight: 5.5 },
    { sym: "ETN",   name: "Eaton Corp plc",             weight: 5.5 },
    { sym: "ENPH",  name: "Enphase Energy",             weight: 5.0 },
    { sym: "ABB",   name: "ABB Ltd ADR",                weight: 4.5 },
    { sym: "VMI",   name: "Valmont Industries",         weight: 4.5 },
    { sym: "SEDG",  name: "SolarEdge Technologies",     weight: 4.0 },
    { sym: "HLIT",  name: "Harmonic Inc",               weight: 4.0 },
    { sym: "NEE",   name: "NextEra Energy",             weight: 3.5 },
    { sym: "AEE",   name: "Ameren Corp",                weight: 3.5 },
    { sym: "FE",    name: "FirstEnergy Corp",           weight: 3.0 },
    { sym: "EVRG",  name: "Evergy Inc",                 weight: 3.0 },
    { sym: "BE",    name: "Bloom Energy",               weight: 2.8 },
    { sym: "PLUG",  name: "Plug Power",                 weight: 2.5 },
    { sym: "FSLR",  name: "First Solar",                weight: 2.5 },
    { sym: "ARRY",  name: "Array Technologies",         weight: 2.0 },
    { sym: "BEP",   name: "Brookfield Renewable",       weight: 2.0 },
    { sym: "CWEN",  name: "Clearway Energy",            weight: 1.8 },
    { sym: "RUN",   name: "Sunrun Inc",                 weight: 1.5 },
    { sym: "NOVA",  name: "Sunnova Energy",             weight: 1.5 },
  ],
  MAGS: [
    { sym: "AAPL",  name: "Apple Inc",                  weight: 14.3 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 14.3 },
    { sym: "GOOGL", name: "Alphabet Inc",               weight: 14.3 },
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 14.3 },
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 14.3 },
    { sym: "META",  name: "Meta Platforms",             weight: 14.3 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 14.3 },
  ],
  URA: [
    { sym: "CCJ",   name: "Cameco Corp",                weight: 24.0 },
    { sym: "NXE",   name: "NexGen Energy Ltd",          weight: 7.5 },
    { sym: "DNN",   name: "Denison Mines Corp",         weight: 5.5 },
    { sym: "UUUU",  name: "Energy Fuels Inc",           weight: 5.0 },
    { sym: "UEC",   name: "Uranium Energy Corp",        weight: 4.5 },
    { sym: "BOSS",  name: "Boss Energy Ltd ADR",        weight: 4.5 },
    { sym: "PALAF", name: "Paladin Energy ADR",         weight: 4.0 },
    { sym: "SRUUF", name: "Sprott Physical Uranium",    weight: 3.5 },
    { sym: "KAP",   name: "Kazatomprom ADR",            weight: 3.5 },
    { sym: "URG",   name: "Ur-Energy Inc",              weight: 3.0 },
    { sym: "EU",    name: "enCore Energy Corp",         weight: 2.5 },
    { sym: "FCUUF", name: "Forum Energy Metals",        weight: 2.5 },
    { sym: "YLIF",  name: "Yellow Cake plc ADR",        weight: 2.0 },
    { sym: "BNNLF", name: "Bannerman Energy",           weight: 2.0 },
    { sym: "DYLLF", name: "Deep Yellow Ltd",            weight: 1.8 },
    { sym: "PTU",   name: "Purepoint Uranium Group",    weight: 1.5 },
    { sym: "HURA",  name: "Horizons Global Uranium",    weight: 1.5 },
    { sym: "URNM",  name: "Sprott Uranium Miners ETF",  weight: 1.3 },
    { sym: "BQSSF", name: "92 Energy Ltd",              weight: 1.0 },
    { sym: "PENMF", name: "Peninsula Energy Ltd",       weight: 1.0 },
  ],
  // Physical ETFs — no stock holdings
  GLD:  null,
  IBIT: null,
};

export default async function handler(req, res) {
  const sym = (req.query.symbol || "").trim().toUpperCase();
  if (!sym) return res.status(400).json({ error: "no symbol" });

  if (STATIC[sym] === null) {
    res.setHeader("Cache-Control", "s-maxage=86400");
    return res.json({ sym, holdings: [], physical: true });
  }

  if (STATIC[sym]) {
    res.setHeader("Cache-Control", "s-maxage=86400");
    return res.json({ sym, holdings: STATIC[sym] });
  }

  return res.status(404).json({ error: "no holdings data for " + sym });
}
