// Static ETF holdings — top 20 per fund
// Data sourced from StockAnalysis, Global X, iShares, VanEck — May 2026

const STATIC = {
  VOO: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 7.31 },
    { sym: "AAPL",  name: "Apple Inc",                  weight: 6.63 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 4.92 },
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 3.47 },
    { sym: "GOOGL", name: "Alphabet Inc Class A",       weight: 3.00 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 2.56 },
    { sym: "GOOG",  name: "Alphabet Inc Class C",       weight: 2.46 },
    { sym: "META",  name: "Meta Platforms",             weight: 2.40 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 1.92 },
    { sym: "BRK.B", name: "Berkshire Hathaway B",       weight: 1.57 },
    { sym: "JPM",   name: "JPMorgan Chase",             weight: 1.50 },
    { sym: "LLY",   name: "Eli Lilly & Co",             weight: 1.40 },
    { sym: "V",     name: "Visa Inc",                   weight: 1.25 },
    { sym: "UNH",   name: "UnitedHealth Group",         weight: 1.15 },
    { sym: "XOM",   name: "Exxon Mobil Corp",           weight: 1.10 },
    { sym: "COST",  name: "Costco Wholesale",           weight: 0.98 },
    { sym: "MA",    name: "Mastercard Inc",             weight: 0.95 },
    { sym: "HD",    name: "Home Depot",                 weight: 0.90 },
    { sym: "NFLX",  name: "Netflix Inc",                weight: 0.85 },
    { sym: "PLTR",  name: "Palantir Technologies",      weight: 0.80 },
  ],
  XLK: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 14.48 },
    { sym: "AAPL",  name: "Apple Inc",                  weight: 12.20 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 9.22 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 5.93 },
    { sym: "MU",    name: "Micron Technology",          weight: 4.74 },
    { sym: "AMD",   name: "Advanced Micro Devices",     weight: 4.07 },
    { sym: "INTC",  name: "Intel Corp",                 weight: 3.29 },
    { sym: "CSCO",  name: "Cisco Systems",              weight: 2.68 },
    { sym: "PLTR",  name: "Palantir Technologies",      weight: 2.44 },
    { sym: "LRCX",  name: "Lam Research Corp",          weight: 2.36 },
    { sym: "QCOM",  name: "Qualcomm Inc",               weight: 2.20 },
    { sym: "AMAT",  name: "Applied Materials",          weight: 2.10 },
    { sym: "KLAC",  name: "KLA Corporation",            weight: 2.00 },
    { sym: "NOW",   name: "ServiceNow Inc",             weight: 1.90 },
    { sym: "INTU",  name: "Intuit Inc",                 weight: 1.80 },
    { sym: "ACN",   name: "Accenture plc",              weight: 1.70 },
    { sym: "TXN",   name: "Texas Instruments",          weight: 1.60 },
    { sym: "ORCL",  name: "Oracle Corp",                weight: 1.50 },
    { sym: "MRVL",  name: "Marvell Technology",         weight: 1.40 },
    { sym: "IBM",   name: "IBM Corp",                   weight: 1.30 },
  ],
  XLY: [
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 28.47 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 18.55 },
    { sym: "HD",    name: "Home Depot",                 weight: 5.23 },
    { sym: "TJX",   name: "TJX Companies",              weight: 3.96 },
    { sym: "MCD",   name: "McDonald's Corp",            weight: 3.80 },
    { sym: "LOW",   name: "Lowe's Companies",           weight: 3.50 },
    { sym: "LULU",  name: "Lululemon Athletica",        weight: 2.80 },
    { sym: "NKE",   name: "Nike Inc",                   weight: 2.40 },
    { sym: "SBUX",  name: "Starbucks Corp",             weight: 2.20 },
    { sym: "ULTA",  name: "Ulta Beauty",                weight: 2.10 },
    { sym: "ABNB",  name: "Airbnb Inc",                 weight: 1.90 },
    { sym: "RCL",   name: "Royal Caribbean Cruises",    weight: 1.80 },
    { sym: "CMG",   name: "Chipotle Mexican Grill",     weight: 1.70 },
    { sym: "RH",    name: "RH (Restoration Hardware)",  weight: 1.65 },
    { sym: "ORLY",  name: "O'Reilly Automotive",        weight: 1.60 },
    { sym: "GM",    name: "General Motors",             weight: 1.50 },
    { sym: "F",     name: "Ford Motor Company",         weight: 1.40 },
    { sym: "HLT",   name: "Hilton Worldwide Holdings",  weight: 1.30 },
    { sym: "MAR",   name: "Marriott International",     weight: 1.20 },
    { sym: "AZO",   name: "AutoZone Inc",               weight: 1.10 },
  ],
  XLF: [
    { sym: "BRK.B", name: "Berkshire Hathaway B",       weight: 11.75 },
    { sym: "JPM",   name: "JPMorgan Chase",             weight: 11.24 },
    { sym: "V",     name: "Visa Inc",                   weight: 7.59 },
    { sym: "MA",    name: "Mastercard Inc",             weight: 5.77 },
    { sym: "BAC",   name: "Bank of America",            weight: 4.73 },
    { sym: "WFC",   name: "Wells Fargo",                weight: 4.50 },
    { sym: "GS",    name: "Goldman Sachs",              weight: 3.50 },
    { sym: "AXP",   name: "American Express",           weight: 3.30 },
    { sym: "MS",    name: "Morgan Stanley",             weight: 3.00 },
    { sym: "SPGI",  name: "S&P Global Inc",             weight: 2.50 },
    { sym: "BLK",   name: "BlackRock Inc",              weight: 2.20 },
    { sym: "SCHW",  name: "Charles Schwab",             weight: 2.00 },
    { sym: "PGR",   name: "Progressive Corp",           weight: 1.90 },
    { sym: "CB",    name: "Chubb Ltd",                  weight: 1.80 },
    { sym: "C",     name: "Citigroup Inc",              weight: 1.70 },
    { sym: "USB",   name: "U.S. Bancorp",               weight: 1.50 },
    { sym: "COF",   name: "Capital One Financial",      weight: 1.40 },
    { sym: "AON",   name: "Aon plc",                    weight: 1.30 },
    { sym: "MMC",   name: "Marsh & McLennan",           weight: 1.20 },
    { sym: "ICE",   name: "Intercontinental Exchange",  weight: 1.10 },
  ],
  XLI: [
    { sym: "CAT",   name: "Caterpillar Inc",            weight: 7.83 },
    { sym: "GE",    name: "GE Aerospace",               weight: 5.59 },
    { sym: "GEV",   name: "GE Vernova Inc",             weight: 5.49 },
    { sym: "RTX",   name: "RTX Corporation",            weight: 4.32 },
    { sym: "BA",    name: "Boeing Company",             weight: 3.28 },
    { sym: "UBER",  name: "Uber Technologies",          weight: 2.93 },
    { sym: "UNP",   name: "Union Pacific Corp",         weight: 2.85 },
    { sym: "HON",   name: "Honeywell International",    weight: 2.84 },
    { sym: "DE",    name: "Deere & Company",            weight: 2.81 },
    { sym: "ETN",   name: "Eaton Corp plc",             weight: 2.75 },
    { sym: "WM",    name: "Waste Management",           weight: 2.20 },
    { sym: "LMT",   name: "Lockheed Martin",            weight: 2.10 },
    { sym: "NSC",   name: "Norfolk Southern",           weight: 1.90 },
    { sym: "CSX",   name: "CSX Corporation",            weight: 1.80 },
    { sym: "ITW",   name: "Illinois Tool Works",        weight: 1.70 },
    { sym: "CTAS",  name: "Cintas Corp",                weight: 1.60 },
    { sym: "GD",    name: "General Dynamics",           weight: 1.50 },
    { sym: "PCAR",  name: "PACCAR Inc",                 weight: 1.40 },
    { sym: "FDX",   name: "FedEx Corp",                 weight: 1.30 },
    { sym: "MMM",   name: "3M Company",                 weight: 1.20 },
  ],
  XLE: [
    { sym: "XOM",   name: "Exxon Mobil Corp",           weight: 22.30 },
    { sym: "CVX",   name: "Chevron Corp",               weight: 16.63 },
    { sym: "COP",   name: "ConocoPhillips",             weight: 7.03 },
    { sym: "SLB",   name: "SLB",                        weight: 4.70 },
    { sym: "WMB",   name: "Williams Companies",         weight: 4.40 },
    { sym: "EOG",   name: "EOG Resources",              weight: 3.95 },
    { sym: "VLO",   name: "Valero Energy",              weight: 3.60 },
    { sym: "HES",   name: "Hess Corporation",           weight: 3.18 },
    { sym: "KMI",   name: "Kinder Morgan",              weight: 2.85 },
    { sym: "OXY",   name: "Occidental Petroleum",       weight: 2.60 },
    { sym: "HAL",   name: "Halliburton Company",        weight: 2.50 },
    { sym: "MPC",   name: "Marathon Petroleum",         weight: 2.30 },
    { sym: "PSX",   name: "Phillips 66",                weight: 2.20 },
    { sym: "BKR",   name: "Baker Hughes",               weight: 2.00 },
    { sym: "FANG",  name: "Diamondback Energy",         weight: 1.90 },
    { sym: "TRGP",  name: "Targa Resources",            weight: 1.70 },
    { sym: "DVN",   name: "Devon Energy",               weight: 1.50 },
    { sym: "EQT",   name: "EQT Corporation",            weight: 1.30 },
    { sym: "MRO",   name: "Marathon Oil",               weight: 1.20 },
    { sym: "APA",   name: "APA Corporation",            weight: 1.00 },
  ],
  XLV: [
    { sym: "LLY",   name: "Eli Lilly & Co",             weight: 14.71 },
    { sym: "JNJ",   name: "Johnson & Johnson",          weight: 10.36 },
    { sym: "ABBV",  name: "AbbVie Inc",                 weight: 7.05 },
    { sym: "UNH",   name: "UnitedHealth Group",         weight: 6.44 },
    { sym: "MRK",   name: "Merck & Co",                 weight: 5.38 },
    { sym: "AMGN",  name: "Amgen Inc",                  weight: 3.54 },
    { sym: "TMO",   name: "Thermo Fisher Scientific",   weight: 3.42 },
    { sym: "ISRG",  name: "Intuitive Surgical",         weight: 3.09 },
    { sym: "GILD",  name: "Gilead Sciences",            weight: 3.08 },
    { sym: "ABT",   name: "Abbott Laboratories",        weight: 2.80 },
    { sym: "PFE",   name: "Pfizer Inc",                 weight: 2.60 },
    { sym: "SYK",   name: "Stryker Corp",               weight: 2.40 },
    { sym: "DHR",   name: "Danaher Corp",               weight: 2.20 },
    { sym: "VRTX",  name: "Vertex Pharmaceuticals",     weight: 2.00 },
    { sym: "BMY",   name: "Bristol-Myers Squibb",       weight: 1.80 },
    { sym: "BSX",   name: "Boston Scientific",          weight: 1.60 },
    { sym: "CVS",   name: "CVS Health",                 weight: 1.40 },
    { sym: "HCA",   name: "HCA Healthcare",             weight: 1.30 },
    { sym: "MDT",   name: "Medtronic plc",              weight: 1.20 },
    { sym: "ELV",   name: "Elevance Health",            weight: 1.10 },
  ],
  XLP: [
    { sym: "WMT",   name: "Walmart Inc",                weight: 12.11 },
    { sym: "COST",  name: "Costco Wholesale",           weight: 9.53 },
    { sym: "PG",    name: "Procter & Gamble",           weight: 7.11 },
    { sym: "KO",    name: "Coca-Cola Company",          weight: 6.42 },
    { sym: "PM",    name: "Philip Morris International",weight: 5.57 },
    { sym: "MO",    name: "Altria Group",               weight: 4.80 },
    { sym: "MDLZ",  name: "Mondelez International",     weight: 4.70 },
    { sym: "PEP",   name: "PepsiCo Inc",                weight: 4.40 },
    { sym: "CL",    name: "Colgate-Palmolive",          weight: 4.20 },
    { sym: "TGT",   name: "Target Corp",                weight: 3.80 },
    { sym: "KMB",   name: "Kimberly-Clark",             weight: 2.40 },
    { sym: "SYY",   name: "Sysco Corporation",          weight: 1.90 },
    { sym: "STZ",   name: "Constellation Brands",       weight: 1.70 },
    { sym: "HSY",   name: "Hershey Company",            weight: 1.55 },
    { sym: "TSN",   name: "Tyson Foods",                weight: 1.35 },
    { sym: "GIS",   name: "General Mills",              weight: 1.25 },
    { sym: "HRL",   name: "Hormel Foods",               weight: 1.15 },
    { sym: "K",     name: "Kellanova",                  weight: 1.05 },
    { sym: "CAG",   name: "Conagra Brands",             weight: 0.95 },
    { sym: "CPB",   name: "Campbell Soup",              weight: 0.75 },
  ],
  XLB: [
    { sym: "LIN",   name: "Linde plc",                  weight: 14.12 },
    { sym: "NEM",   name: "Newmont Corp",               weight: 7.19 },
    { sym: "NUE",   name: "Nucor Corp",                 weight: 5.85 },
    { sym: "FCX",   name: "Freeport-McMoRan",           weight: 5.01 },
    { sym: "APD",   name: "Air Products & Chemicals",   weight: 4.74 },
    { sym: "VMC",   name: "Vulcan Materials",           weight: 4.71 },
    { sym: "CRH",   name: "CRH plc",                   weight: 4.70 },
    { sym: "CTVA",  name: "Corteva Inc",                weight: 4.58 },
    { sym: "MOS",   name: "Mosaic Company",             weight: 3.75 },
    { sym: "SHW",   name: "Sherwin-Williams",           weight: 3.50 },
    { sym: "ECL",   name: "Ecolab Inc",                 weight: 3.20 },
    { sym: "DOW",   name: "Dow Inc",                    weight: 2.80 },
    { sym: "DD",    name: "DuPont de Nemours",          weight: 2.50 },
    { sym: "PPG",   name: "PPG Industries",             weight: 2.20 },
    { sym: "ALB",   name: "Albemarle Corp",             weight: 2.00 },
    { sym: "CF",    name: "CF Industries",              weight: 1.80 },
    { sym: "EMN",   name: "Eastman Chemical",           weight: 1.60 },
    { sym: "CE",    name: "Celanese Corp",              weight: 1.40 },
    { sym: "RPM",   name: "RPM International",          weight: 1.20 },
    { sym: "IFF",   name: "Intl Flavors & Fragrances",  weight: 1.00 },
  ],
  SMH: [
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 16.81 },
    { sym: "TSM",   name: "Taiwan Semiconductor Mfg",   weight: 10.47 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 7.98 },
    { sym: "INTC",  name: "Intel Corp",                 weight: 7.36 },
    { sym: "AMD",   name: "Advanced Micro Devices",     weight: 6.24 },
    { sym: "ASML",  name: "ASML Holding NV",            weight: 5.01 },
    { sym: "LRCX",  name: "Lam Research Corp",          weight: 4.75 },
    { sym: "KLAC",  name: "KLA Corporation",            weight: 4.58 },
    { sym: "TXN",   name: "Texas Instruments",          weight: 4.46 },
    { sym: "QCOM",  name: "Qualcomm Inc",               weight: 4.38 },
    { sym: "MRVL",  name: "Marvell Technology",         weight: 3.50 },
    { sym: "MU",    name: "Micron Technology",          weight: 3.20 },
    { sym: "ON",    name: "ON Semiconductor",           weight: 2.80 },
    { sym: "AMAT",  name: "Applied Materials",          weight: 2.60 },
    { sym: "NXPI",  name: "NXP Semiconductors",         weight: 2.40 },
    { sym: "ADI",   name: "Analog Devices",             weight: 2.20 },
    { sym: "MPWR",  name: "Monolithic Power Systems",   weight: 2.00 },
    { sym: "STM",   name: "STMicroelectronics",         weight: 1.80 },
    { sym: "ENTG",  name: "Entegris Inc",               weight: 1.60 },
    { sym: "WOLF",  name: "Wolfspeed Inc",              weight: 1.20 },
  ],
  IGV: [
    { sym: "ORCL",  name: "Oracle Corp",                weight: 9.16 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 8.47 },
    { sym: "PLTR",  name: "Palantir Technologies",      weight: 7.98 },
    { sym: "CRM",   name: "Salesforce Inc",             weight: 6.67 },
    { sym: "PANW",  name: "Palo Alto Networks",         weight: 5.72 },
    { sym: "APP",   name: "AppLovin Corp",              weight: 4.88 },
    { sym: "CRWD",  name: "CrowdStrike Holdings",       weight: 4.55 },
    { sym: "ADBE",  name: "Adobe Inc",                  weight: 4.07 },
    { sym: "INTU",  name: "Intuit Inc",                 weight: 4.06 },
    { sym: "SNPS",  name: "Synopsys Inc",               weight: 3.71 },
    { sym: "NOW",   name: "ServiceNow Inc",             weight: 3.50 },
    { sym: "WDAY",  name: "Workday Inc",                weight: 3.30 },
    { sym: "CDNS",  name: "Cadence Design Systems",     weight: 3.10 },
    { sym: "SAP",   name: "SAP SE",                     weight: 2.90 },
    { sym: "DDOG",  name: "Datadog Inc",                weight: 2.70 },
    { sym: "ZS",    name: "Zscaler Inc",                weight: 2.50 },
    { sym: "FTNT",  name: "Fortinet Inc",               weight: 2.30 },
    { sym: "HUBS",  name: "HubSpot Inc",                weight: 2.10 },
    { sym: "OKTA",  name: "Okta Inc",                   weight: 1.90 },
    { sym: "TEAM",  name: "Atlassian Corp",             weight: 1.70 },
  ],
  CLOU: [
    { sym: "DOCN",  name: "DigitalOcean Holdings",      weight: 9.01 },
    { sym: "AKAM",  name: "Akamai Technologies",        weight: 6.34 },
    { sym: "DLR",   name: "Digital Realty Trust",       weight: 5.72 },
    { sym: "TWLO",  name: "Twilio Inc",                 weight: 5.34 },
    { sym: "ZM",    name: "Zoom Video Communications",  weight: 5.27 },
    { sym: "NET",   name: "Cloudflare Inc",             weight: 4.50 },
    { sym: "CRWD",  name: "CrowdStrike Holdings",       weight: 4.20 },
    { sym: "OKTA",  name: "Okta Inc",                   weight: 3.80 },
    { sym: "DDOG",  name: "Datadog Inc",                weight: 3.50 },
    { sym: "SNOW",  name: "Snowflake Inc",              weight: 3.30 },
    { sym: "MDB",   name: "MongoDB Inc",                weight: 3.20 },
    { sym: "WDAY",  name: "Workday Inc",                weight: 3.10 },
    { sym: "ZS",    name: "Zscaler Inc",                weight: 2.90 },
    { sym: "HUBS",  name: "HubSpot Inc",                weight: 2.70 },
    { sym: "CFLT",  name: "Confluent Inc",              weight: 2.50 },
    { sym: "PCTY",  name: "Paylocity Holding",          weight: 2.30 },
    { sym: "BILL",  name: "Bill.com Holdings",          weight: 2.10 },
    { sym: "RNG",   name: "RingCentral Inc",            weight: 1.90 },
    { sym: "BOX",   name: "Box Inc",                    weight: 1.70 },
    { sym: "FIVN",  name: "Five9 Inc",                  weight: 1.50 },
  ],
  CIBR: [
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 9.58 },
    { sym: "PANW",  name: "Palo Alto Networks",         weight: 8.83 },
    { sym: "CRWD",  name: "CrowdStrike Holdings",       weight: 8.79 },
    { sym: "CSCO",  name: "Cisco Systems",              weight: 8.44 },
    { sym: "FTNT",  name: "Fortinet Inc",               weight: 7.12 },
    { sym: "NET",   name: "Cloudflare Inc",             weight: 4.71 },
    { sym: "AKAM",  name: "Akamai Technologies",        weight: 3.68 },
    { sym: "ZS",    name: "Zscaler Inc",                weight: 3.65 },
    { sym: "CHKP",  name: "Check Point Software",       weight: 3.18 },
    { sym: "FFIV",  name: "F5 Inc",                     weight: 3.08 },
    { sym: "S",     name: "SentinelOne",                weight: 3.00 },
    { sym: "CYBR",  name: "CyberArk Software",          weight: 2.80 },
    { sym: "VRNS",  name: "Varonis Systems",            weight: 2.60 },
    { sym: "TENB",  name: "Tenable Holdings",           weight: 2.40 },
    { sym: "GEN",   name: "Gen Digital Inc",            weight: 2.20 },
    { sym: "QLYS",  name: "Qualys Inc",                 weight: 2.00 },
    { sym: "OKTA",  name: "Okta Inc",                   weight: 1.80 },
    { sym: "CACI",  name: "CACI International",         weight: 1.60 },
    { sym: "SAIC",  name: "Science Applications Intl",  weight: 1.40 },
    { sym: "LDOS",  name: "Leidos Holdings",            weight: 1.20 },
  ],
  DTCR: [
    { sym: "DLR",   name: "Digital Realty Trust",       weight: 12.63 },
    { sym: "EQIX",  name: "Equinix Inc",                weight: 12.11 },
    { sym: "AMT",   name: "American Tower Corp",        weight: 11.99 },
    { sym: "CCI",   name: "Crown Castle Inc",           weight: 8.78 },
    { sym: "SBAC",  name: "SBA Communications",         weight: 6.50 },
    { sym: "IRM",   name: "Iron Mountain Inc",          weight: 5.50 },
    { sym: "VRT",   name: "Vertiv Holdings",            weight: 5.00 },
    { sym: "ANET",  name: "Arista Networks",            weight: 4.50 },
    { sym: "SMCI",  name: "Super Micro Computer",       weight: 3.80 },
    { sym: "NTAP",  name: "NetApp Inc",                 weight: 3.50 },
    { sym: "STX",   name: "Seagate Technology",         weight: 3.20 },
    { sym: "WDC",   name: "Western Digital Corp",       weight: 3.00 },
    { sym: "PSTG",  name: "Pure Storage",               weight: 2.80 },
    { sym: "HPE",   name: "Hewlett Packard Enterprise", weight: 2.50 },
    { sym: "DBRG",  name: "DigitalBridge Group",        weight: 2.00 },
    { sym: "CSCO",  name: "Cisco Systems",              weight: 1.80 },
    { sym: "UNIT",  name: "Uniti Group",                weight: 1.50 },
    { sym: "LUMN",  name: "Lumen Technologies",         weight: 1.20 },
    { sym: "CORZ",  name: "Core Scientific",            weight: 1.00 },
    { sym: "ZAYO",  name: "Zayo Group Holdings",        weight: 0.90 },
  ],
  QTUM: [
    { sym: "INTC",  name: "Intel Corp",                 weight: 2.39 },
    { sym: "STM",   name: "STMicroelectronics",         weight: 2.16 },
    { sym: "NOK",   name: "Nokia Oyj ADR",              weight: 2.14 },
    { sym: "MU",    name: "Micron Technology",          weight: 2.02 },
    { sym: "GUCOF", name: "Global Unichip Corp",        weight: 2.01 },
    { sym: "ASML",  name: "ASML Holding NV",            weight: 1.95 },
    { sym: "AMAT",  name: "Applied Materials",          weight: 1.85 },
    { sym: "AVGO",  name: "Broadcom Inc",               weight: 1.80 },
    { sym: "AMD",   name: "Advanced Micro Devices",     weight: 1.75 },
    { sym: "IBM",   name: "IBM Corp",                   weight: 1.65 },
    { sym: "IONQ",  name: "IonQ Inc",                   weight: 1.60 },
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 1.55 },
    { sym: "QCOM",  name: "Qualcomm Inc",               weight: 1.50 },
    { sym: "HON",   name: "Honeywell International",    weight: 1.45 },
    { sym: "RGTI",  name: "Rigetti Computing",          weight: 1.40 },
    { sym: "QBTS",  name: "D-Wave Quantum Inc",         weight: 1.35 },
    { sym: "QUBT",  name: "Quantum Computing Inc",      weight: 1.30 },
    { sym: "TXN",   name: "Texas Instruments",          weight: 1.25 },
    { sym: "LRCX",  name: "Lam Research Corp",          weight: 1.20 },
    { sym: "ARQQ",  name: "Arqit Quantum",              weight: 1.15 },
  ],
  BOTZ: [
    { sym: "ABB",   name: "ABB Ltd ADR",                weight: 8.88 },
    { sym: "KEYENCE",name:"Keyence Corp ADR",           weight: 8.82 },
    { sym: "FANUC", name: "Fanuc Corp ADR",             weight: 8.34 },
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 8.21 },
    { sym: "ISRG",  name: "Intuitive Surgical",         weight: 6.95 },
    { sym: "YASKY", name: "Yaskawa Electric ADR",       weight: 6.20 },
    { sym: "TER",   name: "Teradyne Inc",               weight: 5.50 },
    { sym: "CGNX",  name: "Cognex Corp",                weight: 4.90 },
    { sym: "ROK",   name: "Rockwell Automation",        weight: 4.30 },
    { sym: "PATH",  name: "UiPath Inc",                 weight: 3.80 },
    { sym: "BRKS",  name: "Brooks Automation",          weight: 3.50 },
    { sym: "TRMB",  name: "Trimble Inc",                weight: 3.20 },
    { sym: "AI",    name: "C3.ai Inc",                  weight: 2.80 },
    { sym: "AXON",  name: "Axon Enterprise",            weight: 2.60 },
    { sym: "SMC",   name: "SMC Corp ADR",               weight: 2.40 },
    { sym: "OMRON", name: "Omron Corp ADR",             weight: 2.20 },
    { sym: "KION",  name: "KION Group ADR",             weight: 2.00 },
    { sym: "NVCR",  name: "NovoCure Ltd",               weight: 1.80 },
    { sym: "AIOT",  name: "PowerFleet Inc",             weight: 1.60 },
    { sym: "RBOT",  name: "Vicarious Surgical",         weight: 1.20 },
  ],
  ITA: [
    { sym: "GE",    name: "GE Aerospace",               weight: 19.43 },
    { sym: "RTX",   name: "RTX Corporation",            weight: 15.10 },
    { sym: "BA",    name: "Boeing Company",             weight: 10.25 },
    { sym: "GD",    name: "General Dynamics Corp",      weight: 4.78 },
    { sym: "LHX",   name: "L3Harris Technologies",      weight: 4.66 },
    { sym: "LMT",   name: "Lockheed Martin Corp",       weight: 4.58 },
    { sym: "NOC",   name: "Northrop Grumman",           weight: 4.58 },
    { sym: "TDG",   name: "TransDigm Group",            weight: 4.53 },
    { sym: "HWM",   name: "Howmet Aerospace",           weight: 4.75 },
    { sym: "AXON",  name: "Axon Enterprise",            weight: 2.83 },
    { sym: "TDY",   name: "Teledyne Technologies",      weight: 2.20 },
    { sym: "WWD",   name: "Woodward Inc",               weight: 1.80 },
    { sym: "KTOS",  name: "Kratos Defense & Security",  weight: 1.70 },
    { sym: "HEI",   name: "HEICO Corp",                 weight: 1.60 },
    { sym: "DRS",   name: "Leonardo DRS",               weight: 1.50 },
    { sym: "LDOS",  name: "Leidos Holdings",            weight: 1.30 },
    { sym: "BAH",   name: "Booz Allen Hamilton",        weight: 1.20 },
    { sym: "CW",    name: "Curtiss-Wright Corp",        weight: 1.10 },
    { sym: "SPR",   name: "Spirit AeroSystems",         weight: 1.00 },
    { sym: "HII",   name: "Huntington Ingalls",         weight: 0.90 },
  ],
  UFO: [
    { sym: "PL",    name: "Planet Labs PBC",            weight: 6.16 },
    { sym: "VSAT",  name: "ViaSat Inc",                 weight: 5.90 },
    { sym: "GSAT",  name: "Globalstar Inc",             weight: 5.28 },
    { sym: "SIRI",  name: "Sirius XM Holdings",         weight: 5.05 },
    { sym: "RKLB",  name: "Rocket Lab USA",             weight: 5.02 },
    { sym: "ASTS",  name: "AST SpaceMobile",            weight: 4.80 },
    { sym: "LUNR",  name: "Intuitive Machines",         weight: 4.20 },
    { sym: "IRDM",  name: "Iridium Communications",     weight: 4.00 },
    { sym: "BWXT",  name: "BWX Technologies",           weight: 3.80 },
    { sym: "LMT",   name: "Lockheed Martin Corp",       weight: 3.50 },
    { sym: "NOC",   name: "Northrop Grumman",           weight: 3.20 },
    { sym: "KTOS",  name: "Kratos Defense & Security",  weight: 3.00 },
    { sym: "MNTS",  name: "Momentus Inc",               weight: 2.80 },
    { sym: "BA",    name: "Boeing Company",             weight: 2.50 },
    { sym: "RTX",   name: "RTX Corporation",            weight: 2.30 },
    { sym: "LLAP",  name: "Terran Orbital",             weight: 2.10 },
    { sym: "ASTR",  name: "Astra Space",                weight: 1.80 },
    { sym: "HII",   name: "Huntington Ingalls",         weight: 1.60 },
    { sym: "SPCE",  name: "Virgin Galactic Holdings",   weight: 1.40 },
    { sym: "SATL",  name: "Satellogic Inc",             weight: 1.20 },
  ],
  XBI: [
    { sym: "APLS",  name: "Apellis Pharmaceuticals",    weight: 1.83 },
    { sym: "TVTX",  name: "Travere Therapeutics",       weight: 1.70 },
    { sym: "RVMD",  name: "Revolution Medicines",       weight: 1.66 },
    { sym: "ARWR",  name: "Arrowhead Pharmaceuticals",  weight: 1.47 },
    { sym: "TGTX",  name: "TG Therapeutics",            weight: 1.42 },
    { sym: "RXRX",  name: "Recursion Pharmaceuticals",  weight: 1.38 },
    { sym: "SNDX",  name: "Syndax Pharmaceuticals",     weight: 1.35 },
    { sym: "PCVX",  name: "Vaxcyte Inc",                weight: 1.32 },
    { sym: "REPL",  name: "Replimune Group",            weight: 1.28 },
    { sym: "SRPT",  name: "Sarepta Therapeutics",       weight: 1.25 },
    { sym: "ALNY",  name: "Alnylam Pharmaceuticals",    weight: 1.22 },
    { sym: "CRSP",  name: "CRISPR Therapeutics",        weight: 1.20 },
    { sym: "NTLA",  name: "Intellia Therapeutics",      weight: 1.18 },
    { sym: "BEAM",  name: "Beam Therapeutics",          weight: 1.15 },
    { sym: "VRTX",  name: "Vertex Pharmaceuticals",     weight: 1.12 },
    { sym: "MRNA",  name: "Moderna Inc",                weight: 1.10 },
    { sym: "REGN",  name: "Regeneron Pharmaceuticals",  weight: 1.08 },
    { sym: "GILD",  name: "Gilead Sciences",            weight: 1.05 },
    { sym: "BMRN",  name: "BioMarin Pharmaceutical",    weight: 1.02 },
    { sym: "INCY",  name: "Incyte Corp",                weight: 1.00 },
  ],
  BKCH: [
    { sym: "IREN",  name: "Iris Energy",                weight: 11.45 },
    { sym: "APLD",  name: "Applied Digital Corp",       weight: 9.79 },
    { sym: "COIN",  name: "Coinbase Global",            weight: 9.76 },
    { sym: "BMNR",  name: "Bitmine Immersion Tech",     weight: 8.25 },
    { sym: "WULF",  name: "TeraWulf Inc",               weight: 7.03 },
    { sym: "MSTR",  name: "MicroStrategy Inc",          weight: 6.80 },
    { sym: "MARA",  name: "Marathon Digital Holdings",  weight: 5.50 },
    { sym: "RIOT",  name: "Riot Platforms Inc",         weight: 4.90 },
    { sym: "CORZ",  name: "Core Scientific",            weight: 4.20 },
    { sym: "HUT",   name: "Hut 8 Corp",                weight: 3.80 },
    { sym: "CLSK",  name: "CleanSpark Inc",             weight: 3.50 },
    { sym: "HIVE",  name: "HIVE Digital Technologies",  weight: 3.20 },
    { sym: "BITF",  name: "Bitfarms Ltd",               weight: 3.00 },
    { sym: "SQ",    name: "Block Inc",                  weight: 2.80 },
    { sym: "CIFR",  name: "Cipher Mining Inc",          weight: 2.60 },
    { sym: "GLXY",  name: "Galaxy Digital Holdings",    weight: 2.40 },
    { sym: "BTBT",  name: "Bit Digital Inc",            weight: 2.20 },
    { sym: "ARBK",  name: "Argo Blockchain",            weight: 2.00 },
    { sym: "DMGI",  name: "DMG Blockchain Solutions",   weight: 1.80 },
    { sym: "CAN",   name: "Canaan Inc",                 weight: 1.60 },
  ],
  COPX: [
    { sym: "LUNMF", name: "Lundin Mining Corp",         weight: 6.07 },
    { sym: "GLNCY", name: "Glencore plc ADR",           weight: 6.00 },
    { sym: "SMMYY", name: "Sumitomo Metal Mining ADR",  weight: 5.98 },
    { sym: "KGHPF", name: "KGHM Polska Miedz ADR",     weight: 5.82 },
    { sym: "FCX",   name: "Freeport-McMoRan Inc",       weight: 5.06 },
    { sym: "ANTO",  name: "Antofagasta plc ADR",        weight: 4.90 },
    { sym: "SCCO",  name: "Southern Copper Corp",       weight: 4.70 },
    { sym: "BHP",   name: "BHP Group Ltd ADR",          weight: 4.50 },
    { sym: "TECK",  name: "Teck Resources Ltd",         weight: 4.20 },
    { sym: "HBM",   name: "HudBay Minerals",            weight: 3.80 },
    { sym: "IVPAF", name: "Ivanhoe Mines Ltd",          weight: 3.60 },
    { sym: "CPOEF", name: "Capstone Copper Corp",       weight: 3.40 },
    { sym: "FM",    name: "First Quantum Minerals",     weight: 3.20 },
    { sym: "RIO",   name: "Rio Tinto plc ADR",          weight: 3.00 },
    { sym: "ERO",   name: "ERO Copper Corp",            weight: 2.80 },
    { sym: "VALE",  name: "Vale SA ADR",                weight: 2.60 },
    { sym: "SBSW",  name: "Sibanye Stillwater",         weight: 2.40 },
    { sym: "NGLOY", name: "Anglo American plc ADR",     weight: 2.20 },
    { sym: "NGEXF", name: "NGEx Minerals",              weight: 2.00 },
    { sym: "TLOFF", name: "Trilogy Metals",             weight: 1.80 },
  ],
  REMX: [
    { sym: "MP",    name: "MP Materials Corp",          weight: 8.00 },
    { sym: "LYNAS", name: "Lynas Rare Earths ADR",      weight: 7.00 },
    { sym: "ILUKA", name: "Iluka Resources ADR",        weight: 5.50 },
    { sym: "AMG",   name: "AMG Advanced Metallurgy",    weight: 5.50 },
    { sym: "UMICORE",name:"Umicore SA ADR",             weight: 5.00 },
    { sym: "NMG",   name: "Nouveau Monde Graphite",     weight: 4.50 },
    { sym: "NB",    name: "NioCorp Developments",       weight: 4.00 },
    { sym: "LAC",   name: "Lithium Americas Corp",      weight: 3.50 },
    { sym: "SGML",  name: "Sigma Lithium",              weight: 3.00 },
    { sym: "ALTM",  name: "Arcadium Lithium",           weight: 2.80 },
    { sym: "SLI",   name: "Standard Lithium",           weight: 2.50 },
    { sym: "PLTM",  name: "Piedmont Lithium",           weight: 2.20 },
    { sym: "NOVONIX",name:"Novonix Ltd",                weight: 2.00 },
    { sym: "HPMSF", name: "Hyperion Metals Ltd",        weight: 1.80 },
    { sym: "CRML",  name: "Critical Metals Corp",       weight: 1.60 },
    { sym: "REE",   name: "REE Automotive",             weight: 1.40 },
    { sym: "REEMF", name: "Ucore Rare Metals",          weight: 1.20 },
    { sym: "LITHY", name: "Lithium Chile Inc",          weight: 1.00 },
    { sym: "PGEZF", name: "Patriot Battery Metals",     weight: 0.90 },
    { sym: "AAUKF", name: "Anglo American plc",         weight: 0.80 },
  ],
  GRID: [
    { sym: "ETN",   name: "Eaton Corp plc",             weight: 8.47 },
    { sym: "ABB",   name: "ABB Ltd ADR",                weight: 8.04 },
    { sym: "JCI",   name: "Johnson Controls Intl",      weight: 7.52 },
    { sym: "SU",    name: "Schneider Electric ADR",     weight: 7.21 },
    { sym: "NGG",   name: "National Grid plc ADR",      weight: 7.11 },
    { sym: "LGRDY", name: "Legrand SA ADR",             weight: 6.80 },
    { sym: "ST",    name: "Sensata Technologies",       weight: 6.20 },
    { sym: "XYL",   name: "Xylem Inc",                  weight: 5.90 },
    { sym: "FTV",   name: "Fortive Corp",               weight: 5.50 },
    { sym: "ROK",   name: "Rockwell Automation",        weight: 5.10 },
    { sym: "ITRI",  name: "Itron Inc",                  weight: 4.80 },
    { sym: "PWR",   name: "Quanta Services Inc",        weight: 4.50 },
    { sym: "ENPH",  name: "Enphase Energy",             weight: 4.00 },
    { sym: "VMI",   name: "Valmont Industries",         weight: 3.50 },
    { sym: "SEDG",  name: "SolarEdge Technologies",     weight: 3.20 },
    { sym: "FE",    name: "FirstEnergy Corp",           weight: 2.80 },
    { sym: "EVRG",  name: "Evergy Inc",                 weight: 2.50 },
    { sym: "BEP",   name: "Brookfield Renewable",       weight: 2.20 },
    { sym: "FSLR",  name: "First Solar",                weight: 2.00 },
    { sym: "ARRY",  name: "Array Technologies",         weight: 1.80 },
  ],
  MAGS: [
    { sym: "AAPL",  name: "Apple Inc",                  weight: 14.3 },
    { sym: "MSFT",  name: "Microsoft Corp",             weight: 14.3 },
    { sym: "GOOGL", name: "Alphabet Inc",               weight: 14.3 },
    { sym: "AMZN",  name: "Amazon.com Inc",             weight: 14.3 },
    { sym: "NVDA",  name: "NVIDIA Corp",                weight: 14.3 },
    { sym: "META",  name: "Meta Platforms",             weight: 14.3 },
    { sym: "TSLA",  name: "Tesla Inc",                  weight: 14.3 },
  ],
  URA: [
    { sym: "CCJ",   name: "Cameco Corp",                weight: 22.23 },
    { sym: "OKLO",  name: "Oklo Inc",                   weight: 7.09 },
    { sym: "NXE",   name: "NexGen Energy Ltd",          weight: 6.22 },
    { sym: "UEC",   name: "Uranium Energy Corp",        weight: 5.80 },
    { sym: "KAP",   name: "Kazatomprom ADR",            weight: 4.96 },
    { sym: "UUUU",  name: "Energy Fuels Inc",           weight: 4.24 },
    { sym: "SRUUF", name: "Sprott Physical Uranium",    weight: 4.00 },
    { sym: "DNN",   name: "Denison Mines Corp",         weight: 3.80 },
    { sym: "PALAF", name: "Paladin Energy ADR",         weight: 3.60 },
    { sym: "BOSS",  name: "Boss Energy Ltd ADR",        weight: 3.40 },
    { sym: "URG",   name: "Ur-Energy Inc",              weight: 2.80 },
    { sym: "EU",    name: "enCore Energy Corp",         weight: 2.50 },
    { sym: "YLIF",  name: "Yellow Cake plc ADR",        weight: 2.20 },
    { sym: "BNNLF", name: "Bannerman Energy",           weight: 2.00 },
    { sym: "DYLLF", name: "Deep Yellow Ltd",            weight: 1.80 },
    { sym: "NLR",   name: "VanEck Uranium+Nuclear ETF", weight: 1.60 },
    { sym: "PTU",   name: "Purepoint Uranium Group",    weight: 1.40 },
    { sym: "FCUUF", name: "Forum Energy Metals",        weight: 1.20 },
    { sym: "PENMF", name: "Peninsula Energy Ltd",       weight: 1.00 },
    { sym: "BQSSF", name: "92 Energy Ltd",              weight: 0.80 },
  ],
  // Physical ETFs — no stock holdings
  GLD:  null,
  IBIT: null,
};

export default async function handler(req, res) {
  const sym = (req.query.symbol || "").trim().toUpperCase();
  if (!sym) return res.status(400).json({ error: "no symbol" });

  if (STATIC[sym] === null) {
    res.setHeader("Cache-Control", "s-maxage=86400");
    return res.json({ sym, holdings: [], physical: true });
  }

  if (STATIC[sym]) {
    res.setHeader("Cache-Control", "s-maxage=86400");
    return res.json({ sym, holdings: STATIC[sym] });
  }

  return res.status(404).json({ error: "no holdings data for " + sym });
}
